name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci
        working-directory: 04-using-actions/gha-app

      - name: Run Unit Tests
        run: npm test
        working-directory: 04-using-actions/gha-app
